### ISSUE TITLE
Changing username replaces them with only your username

### ISSUE THREAD

**Issue by DK5208** [chylex/Discord-History-Tracker#40] opened 2018-07-26 19:22 UTC
If another Discord user changes their Discord username _(not server nickname)_ to something else while their old one was still saved in the same log file, the name of the user that changed their username will be replaced by yours.
Also, it seems some channels won't be affected by this if they never posted in there before until after they changed their username.

I'm not sure what happens if _you_ change your own Discord username, as I never have before, but I'd imagine it would have a similar effect or would just update your username in the log like you would expect it to.

I looked through the log file that I had saved using DHT, but I couldn't find anything too obvious that could be causing this.

**Comment by chylex** [comment] 2018-07-26 21:18
I'll check it out, sounds like a weird bug.

**Comment by chylex** [comment] 2018-07-28 00:11
Also, what version of the tracker do you have? It's visible in Settings.

**Comment by ssokolow** [comment] 2019-09-19 10:06
I'm not sure if it's the same bug, but I ran into a similar problem (other party's nick getting replaced by mine) in my log.

Unfortunately, because of your `userindex`-based approach and varying ordering of the `userindex` list, there's a lot of these in the diffs I tried between my older dumps, making it difficult to identify when the bug occurred with trivial shell scripting:

```diff
-                "u": 0
+                "u": 1
```

```diff
-                "u": 1
+                "u": 0
```

**Comment by ssokolow** [comment] 2019-09-19 10:19
OK, I whipped up a quick little Python script to let me identify between which two old copies of the log one of the two user IDs went *down*, and it looks like whatever went wrong happened between these two dumps:

```
-rw-rw-r-- 1 ssokolow ssokolow 1.8M Apr 28 19:14 dht.txt.old.13
-rw-rw-r-- 1 ssokolow ssokolow 2.1M Jul  3 21:59 dht.txt.old.14
```

**Comment by chylex** [comment] 2019-09-19 15:21
File size would definitely be an issue and unfortunately there are no browser APIs for compression (and a third party compression library would've made DHT several times larger and possibly not fit within bookmarklet/URL limits). Browsers can already take a long time to generate the download and run out of memory while tracking messages, which I think is beyond the realm of premature optimizations.

I'll look into the issue more, would be nice to have minimal reproduction steps but I suspect the issue is somewhere in archive combining code.

**Comment by ssokolow** [comment] 2019-09-19 15:25
> Browsers can already take a long time to generate the download and run out of memory while tracking messages, which I think is beyond the realm of premature optimizations.

I only use DHT on a single private conversation per file, but that concern did come to mind. Have you considered support for chunked output as a complement to the default "pause tracking on encountering already-seen messages" behaviour?

**Comment by ssokolow** [comment] 2019-09-19 15:35
As for reproduction code, if you can provide me with something more suitable to batch operation (ideally, something that'll run on the command-line under Node.js), I kept every revision `dht.txt` went through to hedge against just this kind of thing.

**Comment by chylex** [comment] 2019-09-19 15:55
I haven't considered chunked output, DHT started as "save whatever your computer and browser can handle", so I tried to compact the JSON structure so that you could save a reasonable amount of messages (i.e. all of one person's DMs at minimum, up to a few hundred thousand messages).

What the project could really use is unit tests, but I'm barely working on it nowadays because it's low priority and there appear to be much more user-friendly alternatives :P but anyway, I'll go over the code and try to find a reproducible example.

**Comment by ssokolow** [comment] 2019-09-19 16:25
> What the project could really use is unit tests, but I'm barely working on it nowadays

That sounds familiar... though mine being low priority is far less my choice than I'd like. :)

**Comment by ssokolow** [comment] 2019-09-19 16:28
Oh, speaking of which...

> and there appear to be much more user-friendly alternatives

Which ones are you thinking of? Yours was the only Linux-compatible solution that turned up last time I googled around.

**Comment by chylex** [comment] 2019-09-19 16:51
> Which ones are you thinking of? Yours was the only Linux-compatible solution that turned up last time I googled around.

Fair enough, though Discord Chat Exporter has a multiplatform CLI version, which may still be more "user-friendly" than dealing with the mess I made :P. Haven't used it though, so I can't tell.

Anyway I found the bug, or at least one bug - the archive combining code has a safeguard in case a user was missing from the index, and it coerced "undefined" and "0" into the same thing, so a valid user was being considered invalid with a fallback to its original (and now wrong) ID from the other archive.

Stupid mistake on my part, but at least this could only happen when combining archives *after* tracking messages, which is probably why barely anyone noticed because the recommended steps are to upload the archive first and only then start tracking new messages.

Do you remember uploading the archive after tracking, or combining multiple archives together, at the time where diffs show the changes? Otherwise there may be more than 1 issue.

**Comment by ssokolow** [comment] 2019-09-19 17:18
I think I remember doing "upload, track, re-upload" at some point in time for some reason that now escapes me, but my memory for dates and times is terrible.

**Comment by chylex** [comment] 2019-09-19 17:35
Well, the diff looks like what happened in my test case and what happened to OP, but the OP mentioned renamed user accounts which didn't make sense.

I'll push the fix and close the issue, then. Unfortunately the only reliable way to fix corrupted archives is to load the archive and re-track all messages. Even with your full revision history, it'd probably take less time to re-track than to script a fix based on the diffs.

**Closed** 2019-09-19 17:44 UTC

**Comment by ssokolow** [comment] 2019-09-19 18:02
I already re-dumped but, just in case, I might try a little script in the future to be sure.

It shouldn't be too difficult or time-consuming for me to whip up a little Python script which walks through from oldest to newest revision, building its own list of message dicts, and then raise the alarm if, after the process is finished, there are any mismatches between the first appearance of a given message ID and the most recent dump's copy.
