### ISSUE TITLE
Group chat cuts off in archive

### ISSUE THREAD

**Issue by triaddraykin** [chylex/Discord-History-Tracker#209] opened 2023-01-21 01:12 UTC
I have an old (2017-2018) group chat that I'm trying to make available offline and preserve the formatting. On both the old html viewer+.txt format and the modern incarnation of the DHT, it cuts off at a certain message that, as far as I can tell, is perfectly ordinary and no different from the rest. Even filtering to specific dates didn't provide the messages.
I'm unsure how to explain it further, but I'm willing to provide all files and even invite to the group DM for troubleshooting. Attached is the existing archive. 
[Mindwalkarchive.zip](https://github.com/chylex/Discord-History-Tracker/files/10471237/Mindwalkarchive.zip)

**Comment by chylex** [comment] 2023-01-21 04:45
Do you mean it stops tracking at that message, or something else?

**Comment by NevyJones** [comment] 2023-01-22 06:23
Yes, it has also happened to me.
I do not know why but it has skipped several days of content and then continue and so on occasion.
It only happens in the PC version of the program.

In the web version, it works great... but... it doesn't save the image content.

**Comment by chylex** [comment] 2023-01-22 07:15
All DHT really does is scroll up and read messages when Discord loads them, so I can think of two possibilities:
- Something happens in the Discord app where when you scroll up, it skips too far into the past
- There is a bug in DHT that keeps scrolling up even though it should only scroll up once it sees new messages

From your comments I don't know if the issue happens consistently for a specific message, or at least a specific channel, when you try to archive them repeatedly. I need more details.

**Comment by NevyJones** [comment] 2023-01-22 07:30
I did it twice... but usually skipped days. It only happens with the application.

In the web one it was normal.
I can't blame my internet as it loads fast... but... I'm not sure either.

**Comment by NevyJones** [comment] 2023-01-22 07:32
perhaps add a manual scrolling speed?

That is to say that it does not scroll up so fast but only after a certain time.

**Comment by chylex** [comment] 2023-01-22 23:55
There is no "scrolling speed", DHT scrolls once it sees new messages or when it detects you've reached the beginning of the channel. It's possible there is a bug in either of those, if there is then it needs to get fixed, not worked around by introducing arbitrary optional timers.

Can you check the exact amount of messages it skipped? I'm interested if it's a multiple of 50 or close.

**Comment by chylex** [comment] 2023-12-21 03:51
I rewrote how DHT detects when older messages have loaded. Once the app update is released in a few hours, can you please check if the issue is still happening?

**Comment by chylex** [comment] 2024-01-11 05:31
Both the app and browser-only version have the updated message detection. Closing as fixed, if you experience the problem again then feel free to comment and reopen.

**Closed by chylex** 2024-01-11 05:31 UTC
