### ISSUE TITLE
"Cannot see any messages"

### ISSUE THREAD

**Issue by HydePod** [chylex/Discord-History-Tracker#101] opened 2020-05-19 21:41 UTC
the tracker will not save any messages on desktop discord client again, presumably this is the same sort of issue that comes with a fresh discord update

**Comment by chylex** [comment] 2020-05-19 22:03
Cannot reproduce the issue, `DHT v.23` and `Discord Stable 60516 (f6ec4b5)` work, there is no newer Discord Stable version available to me.

**Comment by Imanton1** [comment] 2020-05-19 22:05
Able to reproduce on `DHT v.22`, fixed by updating to `DHT v.23`.

**Closed** 2020-05-20 06:26 UTC
