### ISSUE TITLE
line breaks?

### ISSUE THREAD

**Issue by notthehulk** [chylex/Discord-History-Tracker#215] opened 2023-06-19 04:53 UTC
Hi!  
I'm need to copy and paste my logs from the viewer to a word document and I've come across a big ole' problem... 

When I copy and paste, either it keeps ALL the formatting (bold, italic, etc), but none of the line breaks, 
Or I can post without formatting, and keep the line breaks, but none of the formatting!

Any help you can offer would be really appreciated, I'm not sure how to fix it!

**Comment by chylex** [comment] 2023-06-19 14:21
I don't know, I don't use Word or any other such editor. Any examples of what you're copying and how it looks/should look?

**Comment by notthehulk** [comment] 2023-06-19 18:06
Hmm, that's not ideal!  I wonder why it didn't used to do this, but it is now.

I did try turning off the message formatting in the viewer, and copy/pasted it.  If you paste it without formatting, it's not pretty messy workaround, but it's better than nothing!  But you do have to go through and put in all the bold and italic manually.

**Comment by chylex** [comment] 2023-06-19 18:12
Turning off message formatting displays raw Markdown, there are tools to convert it automatically but I don't have personal experience. The formatted text might be fixable, I'm guessing the issue is that Word does not understand the specific formatting Discord and DHT use for the messages. There's also the possibility of adding ways to export messages into other formats instead of copy/pasting, but there's a lot of possibilities and not enough time :P

**Comment by notthehulk** [comment] 2023-06-19 23:09
Thanks so much for all your help!  DHT is amazing, and I'm so grateful for all the work you've put into it!

**Comment by chylex** [comment] 2024-01-11 05:55
Closing as answered with available workarounds.

**Closed by chylex** 2024-01-11 05:55 UTC
