### ISSUE TITLE
Saving private conversations (direct messages) leads to and error

### ISSUE THREAD

**Issue by eduarcor** [chylex/Discord-History-Tracker#162] opened 2022-02-14 13:12 UTC
"The selected channel is not visible in the channel list." I get this error both with the in the web browser w TamperMonkey when trying to save a private conversation. It worked until now. Now it doesn't work anymore.

**Comment by chylex** [comment] 2022-02-14 13:45
Duplicate of #161.

**Closed by chylex** 2022-02-14 13:45 UTC
