### ISSUE TITLE
Error (Unknown Channel) 

### ISSUE THREAD

**Issue by AnthonyG04** [chylex/Discord-History-Tracker#205] opened 2022-10-08 19:28 UTC
I have been having this issue on the windows program version of Discord History Tracker, where it cannot track messages, and I get an error that says "Error (Unknown Channel)".

**Comment by TheTechRobo** [comment] 2022-10-08 20:52
Update to the latest version

**Comment by AnthonyG04** [comment] 2022-10-08 21:27
Thank you! I wasn't aware that it hadn't been updated. I think seeing an auto-updater in a future update for DHT would be very beneficial.

**Comment by TheTechRobo** [comment] 2022-10-08 22:54
> I think seeing an auto-updater in a future update for DHT would be very beneficial.

#165

**Comment by chylex** [comment] 2022-10-09 04:37
Duplicate of #204.

**Closed by chylex** 2022-10-09 04:37 UTC
