### ISSUE TITLE
discord.com says : The selected channel is not visible in the channel list.

### ISSUE THREAD

**Issue by Hanymrf** [chylex/Discord-History-Tracker#243] opened 2023-12-21 02:36 UTC
Hello mate, i hope you are well
I was using the Option 1: Userscript, to scrap all the messages of every channel, but from 4 days ago, i am not able to scrap it, when i click on DHT-Start tracking ..
I get a pop-up with this message : (discord.com says : The selected channel is not visible in the channel list.) 
i tried the other method but do not work, i also use other laptops and account, but i got the same pop-up message 
please Could you help me??

<img width="806" alt="Screen Shot 2023-12-20 at 9 35 49 PM" src="https://github.com/chylex/Discord-History-Tracker/assets/154484395/d49cb712-d1d8-4018-b5da-6c2bc67337ee">

**Comment by chylex** [comment] 2023-12-21 03:29
Probably duplicate of #240.

**Closed by chylex** 2023-12-21 03:29 UTC
