### ISSUE TITLE
Multiple tupperbox proxies treated as a single one

### ISSUE THREAD

**Issue by MageofMagnolia** [chylex/Discord-History-Tracker#146] opened 2021-07-29 05:37 UTC
When I tried saving messages in a channel with multiple tupperbox proxies, all of the messages were saved as if only one proxy had sent it. I believe it treats the most recent proxy as the sender. It's very confusing to see a single proxy when reading it back.

**Comment by chylex** [comment] 2021-07-29 08:04
Duplicate of #64?

**Comment by MageofMagnolia** [comment] 2021-07-29 22:56
It looks like it could be, my bad!

**Closed** 2021-07-30 05:18 UTC
