### ISSUE TITLE
Unable to track messages in a DM in either the Desktop App or the Browser App

### ISSUE THREAD

**Issue by AugustusDraconus** [chylex/Discord-History-Tracker#229] opened 2023-11-04 12:40 UTC
So usually I use the desktop app on my Windows 10 x64 PC, but lately every time I use Ctrl+Shift+I to open the dev console I get immediately logged out. I am not sure what that's about, but I decided to try the Browser version of discord instead, and I keep getting an error that Discord History Tracker cannot see any messages. I have tried both Chrome and Firefox. I have all my adblockers off for Discord domains. I am not really sure what is going on. Everything was fine, seemingly, before a few weeks ago. I feel that I have read all of the documentation that Chylex has provided, and I have used this software for awhile now. This is the first time I have ever had any issues. I am not sure, but I feel that I may be doing something wrong. Any help would of course be appreciated.

**Comment by chylex** [comment] 2023-11-04 13:46
Which version of DHT are you using?

**Comment by AugustusDraconus** [comment] 2023-11-04 15:08
Apparently 37.2

**Comment by TheTechRobo** [comment] 2023-11-04 15:10
Make sure you're on the latest release: https://github.com/chylex/Discord-History-Tracker/releases/tag/v38

**Comment by AugustusDraconus** [comment] 2023-11-04 15:12
I am sorry guys. You are absolutely right! My bad. Seems to be fine now for the Browser App. Do you have any idea why the Desktop app logs me out when I open the console? Cheers.

**Comment by chylex** [comment] 2023-11-04 16:01
Duplicate of #226.

Idk why the desktop app logs you out, happens to me too and I don't feel like investigating.

**Closed by chylex** 2023-11-04 16:01 UTC

**Comment by chylex** [comment] 2023-11-05 03:43
Discord staff responding to the logout issue: https://www.reddit.com/r/discordapp/comments/17g642q/opening_inspect_element_automatically_restarts/k6fqy20/
