### ISSUE TITLE
does not play well with tupperbox

### ISSUE THREAD

**Issue by shinyjiggly** [chylex/Discord-History-Tracker#210] opened 2023-01-23 05:47 UTC
Hello. I am trying to save roleplay logs in a server that uses the bot known as tupperbox for the purpose of allowing each roleplay character to have their own display name and profile picture, but in the logs saved by this tool, it displays all tupper messages as being from the most recently used one, rather than the variety that they should appear as.
![bloodchildborked](https://user-images.githubusercontent.com/2729922/213972368-d5d38f05-eaac-4d8e-a859-ecc50fbbf8df.png)
This is an example of the output from your tool.

![image](https://user-images.githubusercontent.com/2729922/213972812-ecc34560-dd14-441e-a539-5667cb38e4cd.png)
This is an example of the actual log as seen in discord.

I do hope that this can be fixed eventually, as I am interested in saving these logs in case anything happens to the server that they were sent on. 
Thank you.

**Comment by chylex** [comment] 2023-01-23 07:03
Duplicate of #64.

**Closed by chylex** 2023-01-23 07:03 UTC
