### ISSUE TITLE
Doesn't work on Firefox 59.0.2

### ISSUE THREAD

**Issue by bluefiberbread** [chylex/Discord-History-Tracker#33] opened 2018-04-07 19:25 UTC
It shows up as a sidebar like this

https://puu.sh/zYiqY/c864da3361.jpg

**Comment by chylex** [comment] 2018-04-08 02:08
Did FF 59 remove the "Show bookmark in the sidebar" option? (or whatever it says exactly)

**Comment by chylex** [comment] 2018-04-23 14:56
Closing the issue, bookmarks in Firefox are slightly different from other browsers, the correct way to add DHT into Firefox is explained on the DHT website, so unless 59.0.2 changed the way bookmarks work and the guide doesn't apply anymore, then this is not a bug in DHT.

**Closed by chylex** 2018-04-23 14:56 UTC
